### ISSUE TITLE
1.20 Update

### ISSUE THREAD

**Issue by Ibotmealot** [HolyAntimony/PluralKitMC#7]
This is a wonderful plugin that helps make my server accessible to all. However, it does not seem to work with 1.20. I am testing with only five plugins and the pluralkit commands do not seem to be found as commands. 
![image](https://github.com/Omnipico/PluralKitMC/assets/42391199/6fd1d134-0d03-4a2f-b751-f2dc8702e2b5)

**Comment by Ibotmealot** [comment]
https://mclo.gs/nPAWLyl

**Comment by Allymonies** [comment]
Can you update to the new [0.14.16](https://github.com/Omnipico/PluralKitMC/releases/tag/0.14.16) release and let me know if the issue is resolved? The plugin is now built for 1.20 and might behave better, if this is still an issue it might be a plugin compatibility issue that I'll need to debug.

**Comment by Ibotmealot** [comment]
Plugin is working on git-Purpur-2050 (MC: 1.20.1)*, thank you!

**Comment by Ibotmealot** [comment]
```
[15:21:10] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'PluralKitMC-v0_4_16.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.2
	at org.bukkit.craftbukkit.v1_20_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:380) ~[purpur-1.20.1.jar:git-Purpur-2005]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:119) ~[purpur-1.20.1.jar:git-Purpur-2005]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[purpur-1.20.1.jar:git-Purpur-2005]
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.20.1.jar:git-Purpur-2005]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.20.1.jar:git-Purpur-2005]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.1.jar:git-Purpur-2005]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:518) ~[purpur-1.20.1.jar:git-Purpur-2005]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.20.1.jar:git-Purpur-2005]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.1.jar:git-Purpur-2005]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2005]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
https://mclo.gs/8NLeGjY Was working on my test server, went to add to the main server and it doesn't seem to start up, rip :(

**Comment by Allymonies** [comment]
Looks like this was due to a misconfigured `api-version` in the plugin.yml. It should be fixed now if you re-download the plugin (Which you can do through the spigot website or the [release page on GitHub](https://github.com/Omnipico/PluralKitMC/releases/tag/0.14.16)). Since it's a pretty minor bugfix I'm not going to push out a new release for it. Hopefully this will resolve the issues found here!

**Comment by Ibotmealot** [comment]
> Looks like this was due to a misconfigured `api-version` in the plugin.yml. It should be fixed now if you re-download the plugin (Which you can do through the spigot website or the [release page on GitHub](https://github.com/Omnipico/PluralKitMC/releases/tag/0.14.16)). Since it's a pretty minor bugfix I'm not going to push out a new release for it. Hopefully this will resolve the issues found here!

It works on the main server; thank you so much! Accessibility is a big factor in my community, and this helps us achieve just that.
